#### Classification için breast_cancer verileri

In [8]:
import random
import platform
import sys
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

warnings.filterwarnings("ignore")

SEED=42
random.seed(SEED)
np.random.seed(SEED)

sns.set_theme(style="whitegrid",context ="notebook")
plt.rcParams["figure.figsize"]=(7,4)
plt.rcParams["figure.dpi"] = 110


print(f"python: {sys.version.split()[0]}")
print(f"Platform:{platform.platform()}")
print(f"seaborn: {sns.__version__}")
print(f"pandas: {pd.__version__}")
print(f"numpy: {np.__version__}")
print(f"sklearn: {sklearn.__version__}")

python: 3.10.11
Platform:Windows-10-10.0.26200-SP0
seaborn: 0.13.2
pandas: 2.3.3
numpy: 2.2.6
sklearn: 1.7.2

In [3]:
bc = load_breast_cancer(as_frame=True)
X_clf, y_clf = bc.data, bc.target
X_clf.head(2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

In [4]:
print("Sınıf dağılımı(0=habis, 1= iyi huylu):")
print(y_clf.value_counts().rename({0:"habis",1:"iyi"}))
X_clf.iloc[:,:6].describe().T.round(2)

Sınıf dağılımı(0=habis, 1= iyi huylu):
target
iyi      357
habis    212
Name: count, dtype: int64

,count,mean,std,min,25%,50%,75%,max
mean radius,569.0,14.13,3.52,6.98,11.70,13.37,15.78,28.11
mean texture,569.0,19.29,4.30,9.71,16.17,18.84,21.80,39.28
mean perimeter,569.0,91.97,24.30,43.79,75.17,86.24,104.10,188.50
mean area,569.0,654.89,351.91,143.50,420.30,551.10,782.70,2501.00
mean smoothness,569.0,0.10,0.01,0.05,0.09,0.10,0.11,0.16
mean compactness,569.0,0.10,0.05,0.02,0.06,0.09,0.13,0.35

In [9]:
Xc_train,Xc_test,yc_train,yc_test=train_test_split(X_clf,y_clf,test_size=0.2,random_state=SEED)

#### Modellere train test sokuyoz

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

siniflandiricilar = {
    "Baseline": DummyClassifier(strategy="most_frequent").fit(Xc_train,yc_train),
    "Logistic": LogisticRegression().fit(Xc_train,yc_train),
    "KNN": KNeighborsClassifier().fit(Xc_train,yc_train),
    "Karar ağacı": DecisionTreeClassifier().fit(Xc_train,yc_train),
    "Rastgele orman": RandomForestClassifier().fit(Xc_train,yc_train)
}


satirlar =[]

for ad,m in siniflandiricilar.items():
  m.fit(Xc_train,yc_train)
  satirlar.append(
      {
          "Model": ad,
          "Eğitim" : accuracy_score(yc_train,m.predict(Xc_train)),
          "Test": accuracy_score(yc_test,m.predict(Xc_test))
      }
  )

pd.DataFrame(satirlar).set_index("Model").round(3)

                Eğitim   Test
Model
Baseline         0.629  0.623
Logistic         0.949  0.947
KNN              0.941  0.956
Karar ağacı      1.000  0.947
Rastgele orman   1.000  0.965